project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "courses/dlmacro/**"
    - "courses/pnm/index.qmd"
    - "courses/smith-to-simulation/index.qmd"
    - "courses/smith-to-simulation/*.ipynb"
  resources:
    - "courses/pnm/files/**"
    - "courses/pnm/psets/**"
    - "courses/pnm/slides/**"
    - "courses/pnm/notebooks/**"
    - "courses/smith-to-simulation/slides/**"
    - "courses/smith-to-simulation/*.pdf"
    - "courses/smith-to-simulation/book/**"
    - "courses/pnm/book/**"
    - "courses/dlmacro/book/**"

website:
  title: "Juan Zurita"
  site-url: https://juanignaciozurita.github.io/personalwebsite/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Research
        href: research.qmd
      - text: Teaching
        href: teaching.qmd
      - text: CV
        href: cv.qmd
      - text: Open Collaborations
        href: opencollaborations.qmd
      - text: Useful Links
        href: usefullinks.qmd

format:
  html:
    #fontcolor: "darkgreen"
    mainfont: "serif"
    theme: cosmo
    css: styles.css
    toc: true
    
    
