project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "courses/pnm/index.qmd"
    - "courses/pnm/intro.md"
    - "courses/pnm/notebooks/*.ipynb"
    - "courses/dlmacro/index.qmd"
    - "courses/dlmacro/intro.md"
    - "courses/dlmacro/notebooks/*.ipynb"
    - "courses/smith-to-simulation/index.qmd"
    - "courses/smith-to-simulation/intro.md"
    - "!courses/pnm/New Problem Sets/"

website:
  title: "Juan Zurita"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Research
        href: research.qmd
      - text: Teaching
        href: teaching.qmd
      - text: CV
        href: cv.qmd
      - text: Open Collaborations
        href: opencollaborations.qmd
      - text: Useful Links
        href: usefullinks.qmd

format:
  html:
    #fontcolor: "darkgreen"
    mainfont: "serif"
    theme: cosmo
    css: styles.css
    toc: true
    
    
